version: '3'

services:
  frontend:
    build: .
    restart: always
    ports:
      - 4000:80
    container_name: frontend
  
  backend:
    build: ../netspruze
    restart: always
    ports:
      - 8000:8000
    container_name: backend
    env_file:
      - ../netspruze/.env.local
    depends_on:
      - db
    volumes:
      - media:/app/media
    
  db:
    image: postgres:14.4-bullseye
    restart: always
    environment:
          - POSTGRES_USER=netspruze_admin
          - POSTGRES_PASSWORD=KDFhoilakjfne34ifjwf
          - POSTGRES_DB=netspruze
    ports:
      - '10000:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  media:
    driver: local
